### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by mesielepush**
Pull request to merge feature to the development branch, all systems work, UI is beautiful and everything is kind of responsive. Just don't use the app on a movil.

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @mesielepush , 

todo

Please debug the app first to work...it's not working when I click `"NEW"`, also I have console error in the screenshot above

Let's do this before I can look into your code. Also, put a live demo link on your README, just in case error is coming from my side (or other TSEs), this way, they can check that with the live demo

**Comment by mesielepush** [comment]
The last reviewer had a problem that I could not replicate, his error codes show something on utils.js that is not even on my code. The problem as I already had mentioned in the read me could be the localStorage, I add to the read the line 'try to use an incognito tap'. I also add the statement: "localStorage.clear()" at the top of the index.js so if that was the problem it should be fine now.

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @mesielepush 
todo

I am really sorry, I redownloaded the updates (be there any) and re-ran webpack. You have to do the necessary to make the app work. If it has to do with configuration, you can store your code and reconfigure the whole thing (webpack, pm). 

I'm sorry, we can't review an app that doesn't work or maybe works in just incognito-mode. Also like I said earlier, just in case configuration issues are appearing just on the TSE's PC, do include a live-and-working demo link on your README, so that it can be viewed from online

Sorry about that, but please make it work

**Comment by mesielepush** [comment]
I still can't reproduce the error or the last reviewer. I added an online link to avoid the problem.

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED

Hi @mesielepush good job on this project, straightforward interface :+1: However I will need to point out some few things. 

1. see  
There should be a default project that I can just create a todo in without having to create a project.

2. Todos should be editable see

3 [optional] validate all input, currently I can create a todo with an empty date or even completely empty, validate that there are contents and the contents are the correct inputs needed for that column

Please make these changes and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

**Comment by mesielepush** [comment]
1.- There are two default projects each with 3 tasks, they are coded in 'index.js', they just don't appear in the live version.
2.- Update a Todo is now possible by clicking the name of the task. Not in the live version. 
NOTE: The live version was deployed for a problem that one of the reviewers had, it doesn't have these recent changes. Other than the default projects and the update every other part of the code it's exactly the same.

**Review by Oghenebrume50 — APPROVED** [review]
### APPROVED 

Hi @mesielepush this looks good to me :+1: please merge and move on, **This is approved** :slightly_smiling_face:  

**RAPHAEL NORIODE** :mask:

**Pull request merged**
